### ISSUE TITLE
twiss with coupled latice

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#40]
with coupling twiss does not work with error

ocelot/cpbd/optics.py:170: RuntimeWarning: divide by zero encountered in double_scalars
  d_mux = arctan(M[0, 1]/(M[0, 0]*m.beta_x - M[0, 1]*m.alpha_x))

this should be changed to some other warning/error indicating that in coupled case decoupled twiss is not correct

test case:

D0 = Drift (l = 5., id = "D0")
D1 = Drift (l = 1., id = "D1")
D2 = Drift (l = 2.0, id = "D2")

Q1 = Quadrupole (l = 0.1, k1 = -0.6, id = "Q1")
Q2 = Quadrupole (l = 0.1, k1 = 0.01, id = "Q2", tilt = pi/4)

sec = (D0, Q1, D1, Q2, D2)

beam = Beam()
beam.E = 6.0
beam.sigma_E = 0.002
beam.emit_xn = 0.4e-6 
beam.emit_yn = 0.4e-6 
beam.gamma_rel = beam.E / (0.511e-3)
beam.emit_x = beam.emit_xn / beam.gamma_rel
beam.emit_y = beam.emit_yn / beam.gamma_rel
beam.beta_x = 10.0
beam.beta_y = 3.0
beam.alpha_x = 2.0
beam.alpha_y = -2.0

lat = MagneticLattice(sec)
tw0 = Twiss(beam)
tws=twiss(lat, tw0, nPoints = 1000)

**Comment by sergey-tomin** [comment]
this is warning and it works on my laptop. anyway here must be checking to avoid divided by zero. 
![figure_1](https://cloud.githubusercontent.com/assets/7983571/10257088/ac1bc50e-6955-11e5-94f8-39962d6e2148.png)

**Comment by iagapov** [comment]
divide by zero is not a 'warning'. The code works incorrectly, so this needs to be fixed.

**Comment by sergey-tomin** [comment]
divided by zero  is error which crushs the code. Here is not this case see below

print M[2, 3]/M[2, 2]*m.beta_y - M[2, 3]*m.alpha_y, arctan(M[2, 3]/(M[2, 2]*m.beta_y - M[2, 3]*m.alpha_y))

5.45502412182 0.00111206462467
6.07237322199 0.00123637344116
/home/sergey/Dropbox/DESY/repository/ocelot/cpbd/optics.py:170: RuntimeWarning: divide by zero encountered in double_scalars
  d_mux = arctan(M[0, 1]/(M[0, 0]*m.beta_x - M[0, 1]*m.alpha_x))
6.69011365804 0.00136045838756
7.30828567367 0.00148433007011

**Comment by iagapov** [comment]
stranhe. Why does devide by zero not cause code to crash. Anyway it has nothing to do with coupliong

**Comment by sergey-tomin** [comment]
done
