### ISSUE TITLE
restructure

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#42]
remove ocelot.rad 
remove ocelot.lib and move ocelot.lib.genera -> ocelot.genera
consider renaming genera -> sr to improve understandability, but not necessarily

**Comment by sergey-tomin** [comment]
done:
1. moved PyGenera -> ocelot.rad
2. CppGenera left in the same folder  ocelot.lib.genera 
3. moved rad.sr.py -> rad.undulator_params.  Required refactoring for work with Genesis.
4. removed ocelot.fel 
5. moved ocelot.fel.fel.py -> ocelot.rad 
6. ocelot.commen.screen.py was merged with em_screen and moved to ocelot.rad.screen.py
7. created ocelot.gui.sr_plot.py for plotting fluxes, spectrums and so on.
