### ISSUE TITLE
FEL simulations: bad matching of the slice with max current at low energy 

### ISSUE THREAD

**Issue by ggeloni** [iagapov/ocelot#43]
Script enclosed. Bad matching in both planes.

[SASE3_issue.txt](https://github.com/iagapov/ocelot/files/19223/SASE3_issue.txt)

**Comment by iagapov** [comment]
ocelot matching works.
![issue_test](https://cloud.githubusercontent.com/assets/6952937/11269297/6915affa-8eb6-11e5-823c-ce287bc72918.png)

Need to check what happens in genesis

**Comment by iagapov** [comment]
done by Sergey at some point
