### ISSUE TITLE
plot sextupole in gui.accelerator

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#48]
from ocelot import *
from ocelot.gui.accelerator import *

d2 = Drift(l=1.0)
sf1 = Sextupole(l=0.25, k2= 260)

beam = Beam()
beam.E = 5.0
beam.sigma_E = 0.002
beam.beta_x = 1
beam.beta_y = 1

tw0 = Twiss(beam)

lat = MagneticLattice( (d2,sf1,d2))

tws=twiss(lat, Twiss(beam), nPoints = 1000)

plot_opt_func(lat, tws)

plt.show()

**Comment by sergey-tomin** [comment]
fixed
