### ISSUE TITLE
2nd order tracking with tilted quads

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#52]
from ocelot import *

from ocelot.gui.accelerator import *
from ocelot.cpbd.chromaticity import *
from pylab import *

np.set_printoptions(precision=2, suppress=True, linewidth=120)

from pylab import *
from scipy.optimize import *

def ellipse_from_twiss(emit, beta, alpha):
    phi = 2*pi * np.random.rand()
    #u = np.random.rand()
    #a = sqrt(-2*np.log( (1-u)) * emit)
    a = sqrt(emit)
    x = a * sqrt(beta) * cos(phi)
    xp = -a / sqrt(beta) * ( sin(phi) + alpha * cos(phi) )
    return (x, xp)

beam = Beam()
beam.E = 5.0
beam.sigma_E = 0.002
beam.beta_x = 7
beam.beta_y = 5

d1 = Drift(l=1.0)
d2 = Drift(l=4.0)
d3 = Drift(l=4.0)
d4 = Drift(l=0.1)
d5 = Drift(l=1.0)

q1 = Quadrupole(l=0.1, k1 = 1.0, tilt= pi/4)
q2 = Quadrupole(l=0.1, k1 = -5.0, tilt= pi/4)
q3 = Quadrupole(l=0.1, k1 = 1.0, tilt= pi/4)

q1.k1 = -3.30038348729 
q2.k1 = -4.5061442331 
q3.k1 = 1.79650755579

tw0 = Twiss(beam)

l_half = (q1,d2,q2,d3,q3,d4)
lat = MagneticLattice( ( l_half, l_half[::-1] ) )

print lattice_transfer_map(lat, beam.E)

n = 1000

plist = []

for i in range(n):
    x, px = ellipse_from_twiss(7.e-6, tw0.beta_x, tw0.alpha_x)
    y, py = 0, 0
    plist.append(Particle(x=x, px=px, y=y, py=py))

figx = plt.figure('x')
axx = figx.add_subplot(111)
axx.plot([p.x for p in plist], [p.px for p in plist],'b.')
figy=plt.figure('y')
axy = figy.add_subplot(111)
axy.plot([p.y for p in plist], [p.py for p in plist],'b.')

navi = Navigator()
track(lat, plist, dz=lat.totalLen, navi=navi, order=2)

axx.plot([p.x for p in plist], [p.px for p in plist],'r.')
axy.plot([p.y for p in plist], [p.py for p in plist],'g.')

plt.show()

**Comment by sergey-tomin** [comment]
fixed. Branch "python3"
