### ISSUE TITLE
matching does not work

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#58]
matching does not work

e.g. see demos/dba_match.py

use only 

vars = [q1,q2,q3]

**Comment by sergey-tomin** [comment]
now it is better

**Comment by iagapov** [comment]
test case in email

**Comment by iagapov** [comment]
in the future, please don't close issues after fixing a bug. They fix is to be tested first and closed only after that by the person who opened the issue.

**Comment by sergey-tomin** [comment]
matching works. Update Ocelot OR problem is in your script.

**Comment by iagapov** [comment]
please check the example I sent you carefully and please don't close issues until they are checked!
