### ISSUE TITLE
MethodTM

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#59]
this code is in error, correct

class MethodTM:
    def __init__(self, params=None):
        if params == None:
            self.params = {'global': TransferMap}
        else:
            self.params = params

**Comment by sergey-tomin** [comment]
I do not understand what is wrong?

**Comment by iagapov** [comment]
what if params not empty but 'globals' is not there?

**Comment by sergey-tomin** [comment]
fixed
